### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by vsc-github** [pinterest/bonsai#31] opened 2017-06-07 14:01 UTC
Uploading my stats.json file breaks the app. The error in the console is 
```
Uncaught TypeError: Cannot read property 'reduce' of undefined
    at a (getEntryHeirarchy.js:30)
    at s (getEntryHeirarchy.js:97)
    at o (fullModuleData.js:35)
    at t.value (Stats.js:41)
    at d._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:799)
    at d._renderValidatedComponent (ReactCompositeComponent.js:822)
    at d.performInitialMount (ReactCompositeComponent.js:362)
    at d.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at Object.updateChildren (ReactChildReconciler.js:121)
```
Probably its because of I have multiple webpack configurations. Here's my [ webpack config file](http://pasted.co/70509308) .

However my stats.json file works perfectly fine at http://webpack.github.io/analyse/

**Comment by ryan953** [comment] 2017-06-07 18:00
I noticed that reduce thing happening too while I was looking at #27, I was testing a few different configs and I'll have a fix for multi-config's up next. 

In the mean time you can us a wrapper for your config file as a workaround, something like this:

```bash
# normal build uses the multi-target config:
$ webpack --config webpack.conf.js

# stats build uses a wrapper:
$ webpack --json --config webpack-browser.conf.js > stats-browser.json
```

Where `webpack-browser.conf.js` contains:
```javascript
var config = require('webpack.conf.js');
module.export = config[0];
```
It has been tough to find meaningful names for different configs inside a multi-config stats file. So it might be a reasonable long term option to stick with the wrapper thing because you can redirect output to a well named file like `stats-browser.json` and keep it separate from the sibling `stats-node.json` file.

**Comment by ryan953** [comment] 2017-06-07 18:00
Duplicate of #27, closing.

**Closed by ryan953** 2017-06-07 18:00 UTC
Labels: duplicate
